version: '3.3'
name: foodgram

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10-alpine
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    container_name: foodgram_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media/
    
  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    container_name: foodgram_nginx
    build: ../infra
    # image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:
