# Generated by Django 3.2.3 on 2023-07-17 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230717_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента должно быть положительным числом')], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
