# Generated by Django 3.2.3 on 2023-07-26 08:24

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[recipes.validators.validate_cooking_time], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
