# Generated by Django 3.2.3 on 2023-07-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_unique_user_author_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
